In [2]:
import numpy as np
from scipy.optimize import fsolve
from matplotlib import pyplot as plt
import pandas as pd

In [3]:
#Composition specifications:
#order         C;   H;  O;  N;  P;  Na;   

S1 = np.array([1,1.854,0.48,0.095,0.0036,0.0016])
S2 = np.array([1,1.75,0.59,0.125,0.005825,0.00172])
S3 = np.array([1,1.46,0.6,0.02,0.0025,0.0023])
S4 = np.array([1,1.7,0.75,0.02,0.0275,0.00118])
S5 = np.array([1,1.8,0.5,0.08,0.02,0])
S6 = np.array([1,1.7,0.55,0.13,0.02,0])

In [ ]:
wetFractionFood = 0.6
nonEdibleFraction = 0.6

In [ ]:
kiloJoulesRequired = 9000
#                                     Prot, Fat, Carbs
foodFractionsDryMassBasis = np.array([0.36,0.21,0.43])
energyPerDryGramFoodGroup = np.array([17,38,17])
energyPerDryGramFood = np.sum(foodFractionsDryMassBasis * energyPerDryGramFoodGroup)
massChonDryFoodPerDay = kiloJoulesRequired / energyPerDryGramFood
molsChonDryFoodPerDay = massChonDryFoodPerDay / (MM[0]*S1[0] + MM[1]*S1[1] + MM[2]*S1[2] + MM[3]*S1[3])
massDryFoodPerDay = molsChonDryFoodPerDay * np.sum(MM*S1)

massWetFoodPerDay = massDryFoodPerDay / (1 - wetFractionFood)

massNonEdibleDryFoodPerDay = massDryFoodPerDay / (1 - nonEdibleFraction) * nonEdibleFraction

massNonEdibleWetFoodPerDay = massNonEdibleDryFoodPerDay / (1 - wetFractionFood)

print('Mass dry food per day =',np.round(massDryFoodPerDay,2))
print('Mass wet food per day =',np.round(massWetFoodPerDay,2))
print('Mass dry non-edible food per day =',np.round(massNonEdibleDryFoodPerDay,2))
print('Mass wet non-edible food per day =',np.round(massNonEdibleWetFoodPerDay,2))

In [ ]:
molsDryFoodPerDay = molsChonDryFoodPerDay
molsNonEdibleDryFoodPerDay = massNonEdibleDryFoodPerDay / np.sum(MM * S3)

print('Mols dry food per day =',np.round(molsDryFoodPerDay,3))
print('Mols dry non-edible food per day =',np.round(molsNonEdibleDryFoodPerDay,3))

In [3]:
import numpy as np
#                               P    Na   NH3   H2O   CO2   O2   S1      S3
hydroponics_MatrixA=np.matrix([[0,   0,   0,    0,    1,    0,   1,       1     ],  #C
                               [0,   0,   3,    2,    0,    0,   1.853 ,  1.46  ],  #H
                               [0,   0,   0,    1,    2,    2,   0.479 ,  0.6   ],  #O
                               [0,   0,   1,    0,    0,    0,   0.096 ,  0.02  ],  #N
                               [1,   0,   0,    0,    0,    0,   0.0036,  0.0025],  #P
                               [0,   1,   0,    0,    0,    0,   0.0016,  0.0023],  #Na
                               [0,   0,   0,    0,    0,    0,   1,       0     ],  #S1 fed to ben
                               [0,   0,   0,    0,    0,    0,   0,       1     ]]) #S2 non edible food
hydroponics_MatrixA
                               

matrix([[0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
         0.000e+00, 1.000e+00, 1.000e+00],
        [0.000e+00, 0.000e+00, 3.000e+00, 2.000e+00, 0.000e+00,
         0.000e+00, 1.853e+00, 1.460e+00],
        [0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 2.000e+00,
         2.000e+00, 4.790e-01, 6.000e-01],
        [0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 9.600e-02, 2.000e-02],
        [1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 3.600e-03, 2.500e-03],
        [0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 1.600e-03, 2.300e-03],
        [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 1.000e+00, 0.000e+00],
        [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00]])

In [7]:
hydroponics_MatrixB=np.matrix([0, 0, 0, 0, 0, 0, molsDryFoodPerDay, molsNonEdibleDryFoodPerDay ]).T
hydroponics_MatrixB

matrix([[ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [19.01527202],
        [27.96288091]])

In [8]:
hydroponics_rates=np.linalg.solve(hydroponics_MatrixA, hydroponics_MatrixB)
print(hydroponics_rates)

[[ -0.13836218]
 [ -0.09473906]
 [ -2.38472373]
 [-34.45346699]
 [-46.97815292]
 [ 51.2618645 ]
 [ 19.01527202]
 [ 27.96288091]]
