In [1]:
import numpy as np
from scipy.optimize import fsolve
from matplotlib import pyplot as plt
import pandas as pd

In [2]:
#Composition specifications:
#order         C;   H;  O;  N;  P;  Na;   

S1 = np.array([1,1.854,0.48,0.095,0.0036,0.0016])
S2 = np.array([1,1.75,0.59,0.125,0.005825,0.00172])
S3 = np.array([1,1.46,0.6,0.02,0.0025,0.0023])
S4 = np.array([1,1.7,0.75,0.02,0.0275,0.00118])
S5 = np.array([1,1.8,0.5,0.08,0.02,0])
S6 = np.array([1,1.7,0.55,0.13,0.02,0])

In [3]:
MM = np.array([12,1,16,14,31,23])

In [4]:
wetFractionFood = 0.6
nonEdibleFraction = 0.6

In [5]:
kiloJoulesRequired = 9000
#                                     Prot, Fat, Carbs
foodFractionsDryMassBasis = np.array([0.36,0.21,0.43])
energyPerDryGramFoodGroup = np.array([17,38,17])
energyPerDryGramFood = np.sum(foodFractionsDryMassBasis * energyPerDryGramFoodGroup)
massChonDryFoodPerDay = kiloJoulesRequired / energyPerDryGramFood
molsChonDryFoodPerDay = massChonDryFoodPerDay / (MM[0]*S1[0] + MM[1]*S1[1] + MM[2]*S1[2] + MM[3]*S1[3])
massDryFoodPerDay = molsChonDryFoodPerDay * np.sum(MM*S1)

massWetFoodPerDay = massDryFoodPerDay / (1 - wetFractionFood)

massNonEdibleDryFoodPerDay = massDryFoodPerDay / (1 - nonEdibleFraction) * nonEdibleFraction

massNonEdibleWetFoodPerDay = massNonEdibleDryFoodPerDay / (1 - wetFractionFood)

print('Mass dry food per day =',np.round(massChonDryFoodPerDay,2))
print('Mass wet food per day =',np.round(massWetFoodPerDay,2))
print('Mass dry non-edible food per day =',np.round(massNonEdibleDryFoodPerDay,2))
print('Mass wet non-edible food per day =',np.round(massNonEdibleWetFoodPerDay,2))

Mass dry food per day = 420.36
Mass wet food per day = 1057.73
Mass dry non-edible food per day = 634.64
Mass wet non-edible food per day = 1586.6


In [6]:
molsDryFoodPerDay = molsChonDryFoodPerDay
molsNonEdibleDryFoodPerDay = massNonEdibleDryFoodPerDay / np.sum(MM * S3)

NE_Mass = massChonDryFoodPerDay / 0.4 * 0.6
molsNE = NE_Mass / (12*S3[0] + S3[1] + 16*S3[2] + 14*S3[3])
print(molsNE - molsNonEdibleDryFoodPerDay)

print('Mols dry food per day =',np.round(molsDryFoodPerDay,3))
print('Mols dry non-edible food per day =',np.round(molsNonEdibleDryFoodPerDay,3))

-0.024275160304075172
Mols dry food per day = 18.385
Mols dry non-edible food per day = 27.04


In [7]:
import numpy as np
#                               P    Na   NH3   H2O   CO2   O2   S1      S3
hydroponics_MatrixA=np.matrix([[0,   0,   0,    0,    1,    0,   1,       1     ],  #C
                               [0,   0,   3,    2,    0,    0,   1.853 ,  1.46  ],  #H
                               [0,   0,   0,    1,    2,    2,   0.479 ,  0.6   ],  #O
                               [0,   0,   1,    0,    0,    0,   0.096 ,  0.02  ],  #N
                               [1,   0,   0,    0,    0,    0,   0.0036,  0.0025],  #P
                               [0,   1,   0,    0,    0,    0,   0.0016,  0.0023],  #Na
                               [0,   0,   0,    0,    0,    0,   1,       0     ],  #S1 fed to ben
                               [0,   0,   0,    0,    0,    0,   0,       1     ]]) #S2 non edible food
hydroponics_MatrixA
                               

matrix([[0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
         0.000e+00, 1.000e+00, 1.000e+00],
        [0.000e+00, 0.000e+00, 3.000e+00, 2.000e+00, 0.000e+00,
         0.000e+00, 1.853e+00, 1.460e+00],
        [0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 2.000e+00,
         2.000e+00, 4.790e-01, 6.000e-01],
        [0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 9.600e-02, 2.000e-02],
        [1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 3.600e-03, 2.500e-03],
        [0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 1.600e-03, 2.300e-03],
        [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 1.000e+00, 0.000e+00],
        [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00]])

In [8]:
hydroponics_MatrixB=np.matrix([0, 0, 0, 0, 0, 0, molsDryFoodPerDay, molsNonEdibleDryFoodPerDay ]).T
hydroponics_MatrixB

matrix([[ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [18.38542319],
        [27.03997669]])

In [9]:
hydroponics_rates=np.linalg.solve(hydroponics_MatrixA, hydroponics_MatrixB)
print(hydroponics_rates)

[[ -0.13378747]
 [ -0.09160862]
 [ -2.30580016]
 [-33.31457732]
 [-45.42539987]
 [ 49.56738668]
 [ 18.38542319]
 [ 27.03997669]]


In [10]:
#                       S1     H2O  02   CO2   U    S2       P    Na
ben_MatrixA=np.matrix([[1,     0,   0,   1,    1,   1,       0,   0], #C
                       [1.853, 2,   0,   0,    4,   1.75,    0,   0], #H
                       [0.479, 1,   2,   2,    1,   0.59,    0,   0], #O
                       [0.096, 0,   0,   0,    2,   0.125,   0,   0], #N
                       [0.0036,0,   0,   0,    0,   0.005825,1,   0], #P
                       [0.0016,0,   0,   0,    0,   0.00172, 0,   1], #Na
                       [1,     0,   0,   0,    0,   0,       0,   0], #Food
                       [0,     0,   0,   0,    1,   0,       0,   0]])#Urine
ben_MatrixA

matrix([[1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00,
         1.000e+00, 0.000e+00, 0.000e+00],
        [1.853e+00, 2.000e+00, 0.000e+00, 0.000e+00, 4.000e+00,
         1.750e+00, 0.000e+00, 0.000e+00],
        [4.790e-01, 1.000e+00, 2.000e+00, 2.000e+00, 1.000e+00,
         5.900e-01, 0.000e+00, 0.000e+00],
        [9.600e-02, 0.000e+00, 0.000e+00, 0.000e+00, 2.000e+00,
         1.250e-01, 0.000e+00, 0.000e+00],
        [3.600e-03, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         5.825e-03, 1.000e+00, 0.000e+00],
        [1.600e-03, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         1.720e-03, 0.000e+00, 1.000e+00],
        [1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00],
        [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00]])

In [11]:

ben_MatrixB=np.matrix([[0, 0, 0, 0, 0, 0, molsDryFoodPerDay, 40/60 ]]).T
ben_MatrixB

matrix([[ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [18.38542319],
        [ 0.66666667]])

In [12]:
ben_rates=np.linalg.solve(ben_MatrixA,ben_MatrixB)
print(ben_rates)

[[ 1.83854232e+01]
 [ 3.32090980e+00]
 [-4.81961076e+00]
 [ 5.73458182e+00]
 [ 6.66666667e-01]
 [-2.47866717e+01]
 [ 7.81948390e-02]
 [ 1.32163982e-02]]


In [13]:
# CH40N2 + H2O > CO2 + 2NH3
V_Urine=1.5
mols_NH3=ben_rates[4]*2
conc_NH3=mols_NH3/V_Urine
print(conc_NH3,'mol/L')


[[0.88888889]] mol/L
